version: 2.1

orbs:  
  python: circleci/python@1.0.0

jobs:  
  build-and-test:    
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command:
            python3 -m venv env           
            .\env\Scripts\activate 
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
  deploy:
    required:
      - machine 
    executor:
      name: python/default
      tag: '3.7'
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a algo-lib web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a algo-lib web
    
workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          filters:            
            branches:
              only:
                - main
      - deploy:
          filters:            
            branches:
              only:
                - main
